version = 0.1
[default.deploy.parameters]
stack_name = "leyesApp"
resolve_s3 = true
s3_prefix = "leyesApp"
region = "us-east-1"
confirm_changeset = true
image_repositories = []
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM"
disable_rollback = false
