AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-python3.10

  Sample SAM Template for lambda-python3.10

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Resources:
  leyesApp:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Role: arn:aws:iam::533267042808:role/LambdaExcutionRole
      CodeUri: leyesApp/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64


